alias: Heizung – Temperatur Steuerung
description: Regelt die Gasheizung anhand der Raumtemperatur, wenn Klima aus ist
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.haus_temperatur_durchschnitt
    above: 22
    id: zu_warm
  - trigger: numeric_state
    entity_id:
      - sensor.wohnzimmer_temperatur
      - sensor.johanna_temperatur
      - sensor.schlafzimmer_temperatur_2
      - sensor.sophia_temperatur
    below: 20.5
    id: zu_kalt
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - trigger: time
    at: "22:15:00"
    id: zeit
conditions:
  - condition: state
    entity_id: input_boolean.temp_steuerung
    state: "on"
  - condition: state
    entity_id: input_boolean.klima_status
    state: "off"
  - condition: time
    after: "06:00:00"
    before: "22:30:00"
    enabled: false
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - zu_warm
        sequence:
          - action: switch.turn_off
            target:
              entity_id: switch.heizung
            data: {}
          - action: notify.mobile_app_sven_iphone_15
            data:
              title: "Heizung sagt:"
              message: Temperatur hoch genug – Heizung AUS 🧊
      - conditions:
          - condition: trigger
            id:
              - zu_kalt
        sequence:
          - action: switch.turn_on
            target:
              entity_id: switch.heizung
            data: {}
          - action: notify.mobile_app_sven_iphone_15
            data:
              title: "Heizung sagt:"
              message: Temperatur unter 20 °C – Heizung AN 🔥
